DROP TABLE IF EXISTS SUBMISSION;
CREATE TABLE SUBMISSION(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    student_id INTEGER NOT NULL,
    module_code VARCHAR(255) NOT NULL,
    assignment_id INTEGER NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    feedback VARCHAR(255)
);
